declare module 'firebase/firestore';
declare module 'lucide-react-native' {
  import type { ComponentType } from 'react';
  import type { SvgProps } from 'react-native-svg';

  export type LucideIcon = ComponentType<SvgProps & {
    size?: number;
    color?: string;
    strokeWidth?: number;
  }>;

  export const Check: LucideIcon;
  export const Lock: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const Building2: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const User: LucideIcon;
  export const BarChart3: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const Dumbbell: LucideIcon;
  export const Home: LucideIcon;
  export const UserCircle: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const BellRing: LucideIcon;
  export const BrainCircuit: LucideIcon;
  export const FileText: LucideIcon;
  export const Flame: LucideIcon;
  export const Gauge: LucideIcon;
  export const Medal: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Salad: LucideIcon;
  export const Trophy: LucideIcon;
  export const Clock3: LucideIcon;
  export const Plus: LucideIcon;
  export const XCircle: LucideIcon;
  export const Award: LucideIcon;
  export const Edit3: LucideIcon;
  export const LogOut: LucideIcon;
  export const Settings: LucideIcon;
  export const Trash2: LucideIcon;
  export const Users: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const X: LucideIcon;
  export const TimerReset: LucideIcon;
  export const Mic: LucideIcon;
  export const Send: LucideIcon;
  export const Sparkles: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const Clock: LucideIcon;
  export const MapPin: LucideIcon;
  export const Megaphone: LucideIcon;
  export const Eye: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const StickyNote: LucideIcon;
  export const NotebookPen: LucideIcon;
  export const Ban: LucideIcon;
  export const Heart: LucideIcon;
  export const Star: LucideIcon;
  export const Search: LucideIcon;
  export const CupSoda: LucideIcon;
  export const Utensils: LucideIcon;
  export const Download: LucideIcon;
  export const Bell: LucideIcon;
  export const Globe2: LucideIcon;
  export const KeyRound: LucideIcon;
  export const Play: LucideIcon;
  export const Video: LucideIcon;
  export const Waves: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const StretchHorizontal: LucideIcon;
  export const Droplets: LucideIcon;
  export const Moon: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const LogIn: LucideIcon;
  export const UserPlus: LucideIcon;
  export const Activity: LucideIcon;
  export const ClipboardCheck: LucideIcon;
  export const ListChecks: LucideIcon;
  export const CalendarPlus: LucideIcon;
  export const Info: LucideIcon;
  export const AlertTriangle: LucideIcon;}